"""baseline: full schema

Revision ID: 1ba68c31c8dd
Revises: 
Create Date: 2026-09-05 04:31:02.731897

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ba68c31c8dd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('businesses',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('industry', sa.String(length=255), nullable=True),
    sa.Column('plan', sa.Enum('free', 'starter', 'professional', 'business', 'enterprise', name='plantier'), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=False),
    sa.Column('brand_color', sa.String(length=16), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_businesses_slug'), 'businesses', ['slug'], unique=True)
    op.create_table('business_hours',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('business_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('weekday', sa.Integer(), nullable=False),
    sa.Column('is_open', sa.Boolean(), nullable=True),
    sa.Column('open_time', sa.Time(), nullable=True),
    sa.Column('close_time', sa.Time(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_business_hours_business_id'), 'business_hours', ['business_id'], unique=False)
    op.create_table('calendar_credentials',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('business_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=True),
    sa.Column('access_token', sa.Text(), nullable=True),
    sa.Column('refresh_token', sa.Text(), nullable=True),
    sa.Column('token_uri', sa.String(length=255), nullable=True),
    sa.Column('scopes', sa.Text(), nullable=True),
    sa.Column('expiry', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_calendar_credentials_business_id'), 'calendar_credentials', ['business_id'], unique=False)
    op.create_table('chatbot_configs',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('business_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('welcome_message', sa.Text(), nullable=True),
    sa.Column('persona_tone', sa.String(length=64), nullable=True),
    sa.Column('business_description', sa.Text(), nullable=True),
    sa.Column('faqs', sa.JSON(), nullable=True),
    sa.Column('services', sa.JSON(), nullable=True),
    sa.Column('lead_questions', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id')
    )
    op.create_table('conversations',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('business_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('channel', sa.String(length=32), nullable=True),
    sa.Column('visitor_id', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scheduling_settings',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('business_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('slot_duration_minutes', sa.Integer(), nullable=False),
    sa.Column('buffer_minutes', sa.Integer(), nullable=False),
    sa.Column('min_notice_minutes', sa.Integer(), nullable=False),
    sa.Column('max_advance_days', sa.Integer(), nullable=False),
    sa.Column('reminder_offsets_hours', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scheduling_settings_business_id'), 'scheduling_settings', ['business_id'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('business_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('leads',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('business_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('conversation_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('service_interested', sa.String(length=255), nullable=True),
    sa.Column('budget', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('conversation_id')
    )
    op.create_table('messages',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('conversation_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_sessions',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('refresh_token', sa.String(length=1024), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('device_name', sa.String(length=255), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_sessions_refresh_token'), 'user_sessions', ['refresh_token'], unique=True)
    op.create_index(op.f('ix_user_sessions_user_id'), 'user_sessions', ['user_id'], unique=False)
    op.create_table('ai_drafts',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('business_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('lead_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_drafts_business_id'), 'ai_drafts', ['business_id'], unique=False)
    op.create_table('appointments',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('business_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('lead_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('conversation_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('customer_name', sa.String(length=255), nullable=True),
    sa.Column('customer_phone', sa.String(length=32), nullable=True),
    sa.Column('customer_email', sa.String(length=255), nullable=True),
    sa.Column('service', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('scheduled', 'confirmed', 'rescheduled', 'cancelled', 'completed', 'no_show', name='appointmentstatus'), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=True),
    sa.Column('calendar_provider', sa.String(length=32), nullable=True),
    sa.Column('calendar_event_id', sa.String(length=255), nullable=True),
    sa.Column('confirmation_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reminder_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_appointments_business_id'), 'appointments', ['business_id'], unique=False)
    op.create_index(op.f('ix_appointments_end_at'), 'appointments', ['end_at'], unique=False)
    op.create_index(op.f('ix_appointments_lead_id'), 'appointments', ['lead_id'], unique=False)
    op.create_index(op.f('ix_appointments_scheduled_at'), 'appointments', ['scheduled_at'], unique=False)
    op.create_table('email_logs',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('business_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('lead_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('email_type', sa.String(length=32), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('support_tickets',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('business_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('lead_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('issue_summary', sa.Text(), nullable=False),
    sa.Column('priority', sa.String(length=16), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_support_tickets_business_id'), 'support_tickets', ['business_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_support_tickets_business_id'), table_name='support_tickets')
    op.drop_table('support_tickets')
    op.drop_table('email_logs')
    op.drop_index(op.f('ix_appointments_scheduled_at'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_lead_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_end_at'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_business_id'), table_name='appointments')
    op.drop_table('appointments')
    op.drop_index(op.f('ix_ai_drafts_business_id'), table_name='ai_drafts')
    op.drop_table('ai_drafts')
    op.drop_index(op.f('ix_user_sessions_user_id'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_refresh_token'), table_name='user_sessions')
    op.drop_table('user_sessions')
    op.drop_table('messages')
    op.drop_table('leads')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_scheduling_settings_business_id'), table_name='scheduling_settings')
    op.drop_table('scheduling_settings')
    op.drop_table('conversations')
    op.drop_table('chatbot_configs')
    op.drop_index(op.f('ix_calendar_credentials_business_id'), table_name='calendar_credentials')
    op.drop_table('calendar_credentials')
    op.drop_index(op.f('ix_business_hours_business_id'), table_name='business_hours')
    op.drop_table('business_hours')
    op.drop_index(op.f('ix_businesses_slug'), table_name='businesses')
    op.drop_table('businesses')
    # ### end Alembic commands ###
