"""add whatsapp and instagram channel credentials and webhook events

Revision ID: 9d7bce099515
Revises: 1ba68c31c8dd
Create Date: 2026-09-07 23:01:23.545909

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d7bce099515'
down_revision: Union[str, Sequence[str], None] = '1ba68c31c8dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channel_credentials',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('business_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('channel', sa.String(length=32), nullable=False),
    sa.Column('external_account_id', sa.String(length=255), nullable=True),
    sa.Column('access_token', sa.Text(), nullable=True),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('connected_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'channel', name='uq_channel_credentials_business_channel'),
    sa.UniqueConstraint('channel', 'external_account_id', name='uq_channel_credentials_external_account')
    )
    op.create_index(op.f('ix_channel_credentials_business_id'), 'channel_credentials', ['business_id'], unique=False)
    op.create_index(op.f('ix_channel_credentials_external_account_id'), 'channel_credentials', ['external_account_id'], unique=False)
    op.create_table('channel_webhook_events',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('channel', sa.String(length=32), nullable=False),
    sa.Column('external_message_id', sa.String(length=255), nullable=False),
    sa.Column('business_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('received_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('channel', 'external_message_id', name='uq_webhook_events_channel_message')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('channel_webhook_events')
    op.drop_index(op.f('ix_channel_credentials_external_account_id'), table_name='channel_credentials')
    op.drop_index(op.f('ix_channel_credentials_business_id'), table_name='channel_credentials')
    op.drop_table('channel_credentials')
    # ### end Alembic commands ###
