"""rename business to agency

Revision ID: bd6b5e5a3586
Revises: 47250d8827c8
Create Date: 2026-09-11 18:19:56.543650

Hand-written, not autogenerated: autogenerate has no notion of "this is a
rename" - given a table/column named differently from what the current
models declare, it produces a DROP + CREATE pair, which would destroy
every existing row. This migration is a pure, real, reversible RENAME
(table, columns, FK constraints, indexes) - zero data loss, zero
downtime-unsafe operations, matching every other migration in this
project's "additive/safe" discipline even though this one isn't
additive in the schema sense - it's additive in the "your data survives"
sense, which is what actually matters.

Deliberately NOT renamed (matches models.py's own decision, documented
there): the `business_hours` table itself (an operating-hours concept,
not the tenant identity - only ITS `business_id` FK column renames),
`ChatbotConfig.business_description` (a free-text field, not an
identifier), and the two UniqueConstraints
`uq_notification_pref_business_event_channel` /
`uq_channel_credentials_business_channel` (symbolic names only, left
as historical artifacts rather than renamed for no functional benefit).
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd6b5e5a3586'
down_revision: Union[str, Sequence[str], None] = '47250d8827c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Every table that has a business_id FK column pointing at businesses.id,
# in no particular order (rename order doesn't matter - each is an
# independent ALTER on its own table).
TABLES_WITH_BUSINESS_ID = [
    "users", "chatbot_configs", "conversations", "leads", "appointments",
    "business_hours", "scheduling_settings", "calendar_credentials",
    "email_logs", "ai_drafts", "channel_credentials", "channel_webhook_events",
    "support_tickets", "notification_preferences", "gmail_credentials",
    "gmail_pending_actions", "knowledge_documents", "knowledge_chunks",
    "workflows", "workflow_runs", "approval_requests",
]

# Tables that also have an explicit, separately-created index on
# business_id (ix_<table>_business_id) - a couple of tables (conversations,
# email_logs, leads, users, channel_webhook_events) rely on the FK/other
# constraints alone and have no separate named index to rename.
TABLES_WITH_NAMED_INDEX = [
    "ai_drafts", "appointments", "approval_requests", "business_hours",
    "calendar_credentials", "channel_credentials", "gmail_credentials",
    "gmail_pending_actions", "knowledge_chunks", "knowledge_documents",
    "notification_preferences", "scheduling_settings", "support_tickets",
    "workflow_runs", "workflows",
]


def upgrade() -> None:
    op.rename_table("businesses", "agencies")
    op.execute("ALTER INDEX businesses_pkey RENAME TO agencies_pkey")
    op.execute("ALTER INDEX ix_businesses_slug RENAME TO ix_agencies_slug")

    for table in TABLES_WITH_BUSINESS_ID:
        op.alter_column(table, "business_id", new_column_name="agency_id")
        op.execute(f"ALTER TABLE {table} RENAME CONSTRAINT {table}_business_id_fkey TO {table}_agency_id_fkey")

    for table in TABLES_WITH_NAMED_INDEX:
        op.execute(f"ALTER INDEX ix_{table}_business_id RENAME TO ix_{table}_agency_id")

    # chatbot_configs.business_id had unique=True -> an implicit unique
    # constraint, not a plain index.
    op.execute("ALTER TABLE chatbot_configs RENAME CONSTRAINT chatbot_configs_business_id_key TO chatbot_configs_agency_id_key")


def downgrade() -> None:
    op.execute("ALTER TABLE chatbot_configs RENAME CONSTRAINT chatbot_configs_agency_id_key TO chatbot_configs_business_id_key")

    for table in TABLES_WITH_NAMED_INDEX:
        op.execute(f"ALTER INDEX ix_{table}_agency_id RENAME TO ix_{table}_business_id")

    for table in TABLES_WITH_BUSINESS_ID:
        op.execute(f"ALTER TABLE {table} RENAME CONSTRAINT {table}_agency_id_fkey TO {table}_business_id_fkey")
        op.alter_column(table, "agency_id", new_column_name="business_id")

    op.execute("ALTER INDEX ix_agencies_slug RENAME TO ix_businesses_slug")
    op.execute("ALTER INDEX agencies_pkey RENAME TO businesses_pkey")
    op.rename_table("agencies", "businesses")
