"""add buyer marketplace accounts

Revision ID: c08fe49ae740
Revises: bd6b5e5a3586
Create Date: 2026-09-11 18:29:25.285097

Hand-fixed after autogenerate: it flagged ix_knowledge_chunks_embedding_cosine
(the Phase 4 HNSW index, created via raw op.execute() since it isn't
expressible in plain SQLAlchemy column metadata) as "removed" - a false
positive unrelated to this migration, which never touches knowledge_chunks.
That drop/recreate pair has been removed from both upgrade() and
downgrade() below (same fix applied to every prior migration that hit
this same autogenerate quirk).
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c08fe49ae740'
down_revision: Union[str, Sequence[str], None] = 'bd6b5e5a3586'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buyers',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_buyers_email'), 'buyers', ['email'], unique=True)
    op.create_table('buyer_sessions',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('buyer_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('refresh_token', sa.String(length=1024), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('device_name', sa.String(length=255), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['buyer_id'], ['buyers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_buyer_sessions_buyer_id'), 'buyer_sessions', ['buyer_id'], unique=False)
    op.create_index(op.f('ix_buyer_sessions_refresh_token'), 'buyer_sessions', ['refresh_token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_buyer_sessions_refresh_token'), table_name='buyer_sessions')
    op.drop_index(op.f('ix_buyer_sessions_buyer_id'), table_name='buyer_sessions')
    op.drop_table('buyer_sessions')
    op.drop_index(op.f('ix_buyers_email'), table_name='buyers')
    op.drop_table('buyers')
    # ### end Alembic commands ###
