"""add knowledge base and rag

Revision ID: e121ea483fc7
Revises: 26e6ad49bff4
Create Date: 2026-09-08 17:32:58.147664

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = 'e121ea483fc7'
down_revision: Union[str, Sequence[str], None] = '26e6ad49bff4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Confirmed available on this project's Neon instance (0.8.6) - see
    # ARCHITECTURE.md's "Knowledge Base / RAG" section. Idempotent, so this
    # is safe to run again on an environment where it's already enabled.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_documents',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('business_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_type', sa.String(length=16), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('storage_path', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('queued', 'processing', 'ready', 'failed', name='knowledge_document_status'), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('chunk_count', sa.Integer(), nullable=False),
    sa.Column('doc_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_documents_business_id'), 'knowledge_documents', ['business_id'], unique=False)
    op.create_table('knowledge_chunks',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('document_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('business_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True),
    sa.Column('chunk_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_id'], ['knowledge_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'chunk_index', name='uq_knowledge_chunk_document_index')
    )
    op.create_index(op.f('ix_knowledge_chunks_business_id'), 'knowledge_chunks', ['business_id'], unique=False)
    op.create_index(op.f('ix_knowledge_chunks_document_id'), 'knowledge_chunks', ['document_id'], unique=False)
    # ### end Alembic commands ###

    # ANN index for cosine-similarity search (see retrieval.py's use of
    # pgvector's cosine_distance()) - HNSW works well even starting from
    # an empty table (unlike ivfflat, which wants representative data
    # present at CREATE INDEX time), which matches every business starting
    # with zero documents.
    op.execute(
        "CREATE INDEX ix_knowledge_chunks_embedding_cosine ON knowledge_chunks "
        "USING hnsw (embedding vector_cosine_ops)"
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DROP INDEX IF EXISTS ix_knowledge_chunks_embedding_cosine")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_knowledge_chunks_document_id'), table_name='knowledge_chunks')
    op.drop_index(op.f('ix_knowledge_chunks_business_id'), table_name='knowledge_chunks')
    op.drop_table('knowledge_chunks')
    op.drop_index(op.f('ix_knowledge_documents_business_id'), table_name='knowledge_documents')
    op.drop_table('knowledge_documents')
    # ### end Alembic commands ###

    # Confirmed live: Postgres ENUM types created via sa.Enum(...) are
    # separate, named objects that DROP TABLE does not remove - without
    # this, downgrading then re-upgrading fails with "type already
    # exists" on the next CREATE TABLE. Autogenerate never adds this on
    # its own; it has to be explicit.
    sa.Enum(name='knowledge_document_status').drop(op.get_bind(), checkfirst=True)

    # Extension intentionally left in place on downgrade - other tables/
    # environments may depend on it, and CREATE EXTENSION IF NOT EXISTS
    # in upgrade() is already safe to re-run.
